version: '3'

services:
  web:
    image: apollin/article-service-v1:v0.7
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - '8002:8000'
    environment:
      - MONGO_USER=made
      - MONGO_PASSWORD=password
      - MONGO_ADDRESS=db:27017
      - TOKEN_EXPIRATION=7200
    depends_on:
      - db

  cron:
    image: apollin/article-service-v1:v0.7
    command: python -m app.refresh_stats
    environment:
      - MONGO_USER=made
      - MONGO_PASSWORD=password
      - MONGO_ADDRESS=db:27017
      - TOKEN_EXPIRATION=7200
    depends_on:
      - db

  db:
    image: mongo:5.0

    environment:
      - MONGO_INITDB_ROOT_USERNAME=made
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - mongodb-volume:/data/db
      - ./mongo_seed:/mongo_seed
      - ./mongo_seed:/docker-entrypoint-initdb.d
      
  front:
    image: alexcei64/streamlit_made
    ports:
      - '8501:8501'
    environment:
      - WEB_ADDRESS=web:8000
    volumes:
      - ./front:/app
    depends_on:
      - web
      - db

volumes:
        mongodb-volume:
