version: '3'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - '8002:8000'
    environment:
      - MONGO_USER=made
      - MONGO_PASSWORD=password
      - MONGO_ADDRESS=db:27017
    depends_on:
      - db

  db:
    image: mongo:5.0

    environment:
      - MONGO_INITDB_ROOT_USERNAME=made
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - mongodb-volume:/data/db
      - ./mongo_seed:/mongo_seed
      - ./mongo_seed:/docker-entrypoint-initdb.d

volumes:
        mongodb-volume: