version: '3.4'

services:
  web:
    build: ./src
    command: sleep 10 ; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - '8002:8000'
    environment:
      - MONGO_USER=made
      - MONGO_PASSWORD=password
      - MONGO_ADDRESS=db:27017
    depends_on:
      - db

  db:
    image: mongo:5.0

    environment:
      - MONGO_INITDB_ROOT_USERNAME=made
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - mongodb-volume:/data/db
      - ./mongo_seed:/mongo_seed
      - ./mongo_seed:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
        mongodb-volume: